apiVersion: v1
kind: Secret
metadata:
  name: gamestoreapi-secret
  namespace: gamestore
type: Opaque
stringData:
  POSTGRES_CONNECTION_STRING: "Host=postgres-service;Port=5432;Database=GameStore;Username=postgres;Password=gamestore"
  REDIS_CONNECTION_STRING: "redis-service:6379,password=gamestore"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: gamestore
type: Opaque
stringData:
  POSTGRES_PASSWORD: "gamestore"
  POSTGRES_DB: "GameStore"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: "gamestore"
type: Opaque
stringData:
  REDIS_PASSWORD: "gamestore"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: gamestore
data:
  init.sql: |
    -- Any initialization SQL scripts can go here
    -- This will run when PostgreSQL first starts
