apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: gamestore
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: (Aea{AkeWf*WYwk(C96}-Y
  POSTGRES_DB: GameStore
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: gamestore
data:
  init.sql: |
    -- Any initialization SQL scripts can go here
    -- This will run when PostgreSQL first starts
